### ISSUE TITLE
Cannot access to the db property of the instance SQLiteSessionStorage

### ISSUE THREAD

**Issue by william-dandrea** [Shopify/shopify-app-examples#136]
In the file ``web/shopify.js`` : 
```
const dbFile = join(process.cwd(), "database.sqlite");
const sessionDb = new SQLiteSessionStorage(dbFile);
// Initialize SQLite DB
QRCodesDB.db = sessionDb.db;
QRCodesDB.init();

```

We cannot access to the property `sessionDb.db` because the attribute `SQLiteSessionStorage.db` is private : 

``` 
export declare class SQLiteSessionStorage implements SessionStorage {
    private filename;
    private options;
    private db;
    private ready;
    constructor(filename: string, opts?: Partial<SQLiteSessionStorageOptions>);
    storeSession(session: Session): Promise<boolean>;
    loadSession(id: string): Promise<Session | undefined>;
    deleteSession(id: string): Promise<boolean>;
    deleteSessions(ids: string[]): Promise<boolean>;
    findSessionsByShop(shop: string): Promise<Session[]>;
    private hasSessionTable;
    private init;
    private query;
    private databaseRowToSession;
}
```

So, it result with this error : 
```
2022-12-30 17:59:27 | backend  | this.db = this.db ?? new sqlite3.Database(DEFAULT_DB_FILE);
2022-12-30 17:59:27 | backend  |                        ^
2022-12-30 17:59:27 | backend  |
2022-12-30 17:59:27 | backend  | TypeError: Cannot read properties of undefined (reading 'db')
```

**Comment by polashrp** [comment]
it's maybe vs code editor-related error can you change your editor Formate mode select Language mode javascript to `Javascript React` then fix this issue 
![Screenshot from 2023-01-24 12-54-15](https://user-images.githubusercontent.com/18694551/214229907-0e4eb3d7-381f-435f-bfdd-3553eed0ac41.png)

**Comment by SofanaBen** [comment]
@polashrp I tried the solution that you suggested and it didnt work for me. For some reason the db.all() is not being executed properly. Can someone help me with that ?

<img width="531" alt="Screen Shot 2023-02-19 at 6 25 07 AM" src="https://user-images.githubusercontent.com/42274771/219944931-d65a2634-e576-4b51-bddd-27cfd2f70a2c.png">

**Comment by kebabel** [comment]
Hi @polashrp  I had the same Issue.
A quick fix is to change the command to `this.db.db.all(...)`. Since `this.db` contains the connection with the actual db inside.

**Comment by SofanaBen** [comment]
@kebabel That's worked for me. Thanks a lot

**Comment by polashrp** [comment]
Yes, i will fix it, can you share your details with me.

**Comment by jayleo** [comment]
> Hi @SofanaBen I had the same Issue. A quick fix is to change the command to `this.db.db.all(...)`. Since `this.db` contains the connection with the actual db inside.

I was having the same error on running `npm run dev` and @kebabel 's fix works for me.
